apiVersion: apps/v1
kind: Deployment
metadata:
  name: gs-hello-caller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gs-hello-caller
  template:
    metadata:
      labels:
        app: gs-hello-caller
    spec:
      containers:
        - name: gs-hello-caller
          image: yourdockerhubid/hello-caller:latest
          ports:
            - containerPort: 8080
